In [1]:
import torch
import torch.nn as nn

sequence_length = 5
embed_dim = 1
data = torch.tensor([1.2, 1.4, 2.1, 2.6, 3.5], 
                    dtype=torch.float)
print(data)

data = data.reshape(sequence_length, embed_dim)
print(data.shape)

tensor([1.2000, 1.4000, 2.1000, 2.6000, 3.5000])
torch.Size([5, 1])


In [2]:
hidden_dim = 2
rnn = nn.RNN(embed_dim, hidden_dim, batch_first=True)

rnn.bias_ih_l0 = nn.Parameter(torch.tensor([-0.5966,  0.0945]).float())
rnn.bias_hh_l0 = nn.Parameter(torch.tensor([ 0.6599, -0.2662]).float())
rnn.weight_ih_l0 = nn.Parameter(torch.tensor([[ 0.6584],
                                              [-0.1671]]).float())
rnn.weight_hh_l0 = nn.Parameter(torch.tensor([[ 0.5147, -0.1310],
                                              [ 0.6606, -0.1671]]).float())

In [3]:
rnn = nn.RNN(embed_dim, hidden_dim, num_layers=2, batch_first=True)
rnn_output, rnn_hidden = rnn(data)
rnn_output

tensor([[-0.4098, -0.1997],
        [-0.3154, -0.0753],
        [-0.4289, -0.0295],
        [-0.3934,  0.0400],
        [-0.4099,  0.0493]], grad_fn=<SqueezeBackward1>)

In [4]:
rnn_hidden

tensor([[ 0.8449,  0.9931],
        [-0.4099,  0.0493]], grad_fn=<SqueezeBackward1>)